[package]
name = "threaded"
version = "0.1.0"
authors = ["PSTL"]
edition = "2018"

[dependencies]
rand = "0.6.5"
web_server = {path = "../web_server"}

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "benchmark"
harness = false